{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hermes.fullname" . }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
      secretName: {{ .Values.ingress.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: {{ include "hermes.fullname" . }}-control-plane
                port: {number: {{ .Values.controlPlane.service.port }}}
          - path: /ui
            pathType: Prefix
            backend:
              service:
                name: {{ include "hermes.fullname" . }}-control-plane
                port: {number: {{ .Values.controlPlane.service.port }}}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "hermes.fullname" . }}-smart-router
                port: {number: {{ .Values.smartRouter.service.port }}}
{{- end }}
